// ===================================
// `qrcode` ships no type definitions, and @types/qrcode describes the whole
// renderer surface (canvas, PNG, file output) that we deliberately never touch.
// Declared here is only what services/qrLabel.ts actually calls: the pure-JS
// matrix generator. Everything else in the package pulls in fs/canvas and has no
// business in a React Native bundle.
//
// The module is already in the tree as react-native-qrcode-svg's own dependency,
// and that library imports it exactly like this — so the preview component and
// the printed label are generated by one and the same encoder.
// ===================================

declare module 'qrcode' {
  export type QRErrorCorrectionLevel = 'L' | 'M' | 'Q' | 'H';

  export interface QRCodeMatrix {
    /** Side length of the matrix, in modules (e.g. 29 for a version-3 code). */
    size: number;
    /** Row-major, one byte per module: non-zero = dark. Length is size × size. */
    data: Uint8Array;
  }

  export interface QRCodeData {
    modules: QRCodeMatrix;
    version: number;
    errorCorrectionLevel: number;
  }

  export function create(
    text: string,
    options?: { errorCorrectionLevel?: QRErrorCorrectionLevel; version?: number }
  ): QRCodeData;
}
